/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as _authenticatedIndexRouteImport } from './routes/(_authenticated)/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as _authenticatedSwapsRouteImport } from './routes/(_authenticated)/swaps'
import { Route as _authenticatedScheduleRouteImport } from './routes/(_authenticated)/schedule'
import { Route as _authenticatedOvertimeRouteImport } from './routes/(_authenticated)/overtime'
import { Route as _authenticatedMyShiftsRouteImport } from './routes/(_authenticated)/my-shifts'
import { Route as _authenticatedSchedulesCalendarRouteImport } from './routes/(_authenticated)/schedules/calendar'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedIndexRoute = _authenticatedIndexRouteImport.update({
  id: '/(_authenticated)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedSwapsRoute = _authenticatedSwapsRouteImport.update({
  id: '/(_authenticated)/swaps',
  path: '/swaps',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedScheduleRoute = _authenticatedScheduleRouteImport.update({
  id: '/(_authenticated)/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedOvertimeRoute = _authenticatedOvertimeRouteImport.update({
  id: '/(_authenticated)/overtime',
  path: '/overtime',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedMyShiftsRoute = _authenticatedMyShiftsRouteImport.update({
  id: '/(_authenticated)/my-shifts',
  path: '/my-shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedSchedulesCalendarRoute =
  _authenticatedSchedulesCalendarRouteImport.update({
    id: '/(_authenticated)/schedules/calendar',
    path: '/schedules/calendar',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/unauthorized': typeof UnauthorizedRoute
  '/my-shifts': typeof _authenticatedMyShiftsRoute
  '/overtime': typeof _authenticatedOvertimeRoute
  '/schedule': typeof _authenticatedScheduleRoute
  '/swaps': typeof _authenticatedSwapsRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof _authenticatedIndexRoute
  '/schedules/calendar': typeof _authenticatedSchedulesCalendarRoute
}
export interface FileRoutesByTo {
  '/unauthorized': typeof UnauthorizedRoute
  '/my-shifts': typeof _authenticatedMyShiftsRoute
  '/overtime': typeof _authenticatedOvertimeRoute
  '/schedule': typeof _authenticatedScheduleRoute
  '/swaps': typeof _authenticatedSwapsRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof _authenticatedIndexRoute
  '/schedules/calendar': typeof _authenticatedSchedulesCalendarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/unauthorized': typeof UnauthorizedRoute
  '/(_authenticated)/my-shifts': typeof _authenticatedMyShiftsRoute
  '/(_authenticated)/overtime': typeof _authenticatedOvertimeRoute
  '/(_authenticated)/schedule': typeof _authenticatedScheduleRoute
  '/(_authenticated)/swaps': typeof _authenticatedSwapsRoute
  '/auth/login': typeof AuthLoginRoute
  '/(_authenticated)/': typeof _authenticatedIndexRoute
  '/(_authenticated)/schedules/calendar': typeof _authenticatedSchedulesCalendarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/unauthorized'
    | '/my-shifts'
    | '/overtime'
    | '/schedule'
    | '/swaps'
    | '/auth/login'
    | '/'
    | '/schedules/calendar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/unauthorized'
    | '/my-shifts'
    | '/overtime'
    | '/schedule'
    | '/swaps'
    | '/auth/login'
    | '/'
    | '/schedules/calendar'
  id:
    | '__root__'
    | '/unauthorized'
    | '/(_authenticated)/my-shifts'
    | '/(_authenticated)/overtime'
    | '/(_authenticated)/schedule'
    | '/(_authenticated)/swaps'
    | '/auth/login'
    | '/(_authenticated)/'
    | '/(_authenticated)/schedules/calendar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  UnauthorizedRoute: typeof UnauthorizedRoute
  _authenticatedMyShiftsRoute: typeof _authenticatedMyShiftsRoute
  _authenticatedOvertimeRoute: typeof _authenticatedOvertimeRoute
  _authenticatedScheduleRoute: typeof _authenticatedScheduleRoute
  _authenticatedSwapsRoute: typeof _authenticatedSwapsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  _authenticatedIndexRoute: typeof _authenticatedIndexRoute
  _authenticatedSchedulesCalendarRoute: typeof _authenticatedSchedulesCalendarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(_authenticated)/': {
      id: '/(_authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _authenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(_authenticated)/swaps': {
      id: '/(_authenticated)/swaps'
      path: '/swaps'
      fullPath: '/swaps'
      preLoaderRoute: typeof _authenticatedSwapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(_authenticated)/schedule': {
      id: '/(_authenticated)/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof _authenticatedScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(_authenticated)/overtime': {
      id: '/(_authenticated)/overtime'
      path: '/overtime'
      fullPath: '/overtime'
      preLoaderRoute: typeof _authenticatedOvertimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(_authenticated)/my-shifts': {
      id: '/(_authenticated)/my-shifts'
      path: '/my-shifts'
      fullPath: '/my-shifts'
      preLoaderRoute: typeof _authenticatedMyShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(_authenticated)/schedules/calendar': {
      id: '/(_authenticated)/schedules/calendar'
      path: '/schedules/calendar'
      fullPath: '/schedules/calendar'
      preLoaderRoute: typeof _authenticatedSchedulesCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  UnauthorizedRoute: UnauthorizedRoute,
  _authenticatedMyShiftsRoute: _authenticatedMyShiftsRoute,
  _authenticatedOvertimeRoute: _authenticatedOvertimeRoute,
  _authenticatedScheduleRoute: _authenticatedScheduleRoute,
  _authenticatedSwapsRoute: _authenticatedSwapsRoute,
  AuthLoginRoute: AuthLoginRoute,
  _authenticatedIndexRoute: _authenticatedIndexRoute,
  _authenticatedSchedulesCalendarRoute: _authenticatedSchedulesCalendarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
