export const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  STAFF: 'STAFF'
} as const

export const SHIFT_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  CANCELLED: 'CANCELLED'
} as const

export const SWAP_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED'
} as const

export const DROP_STATUS = {
  PENDING: 'PENDING',
  CLAIMED: 'CLAIMED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED'
} as const

export const VIOLATION_CODES = {
  OVERLAP: 'OVERLAP',
  INSUFFICIENT_REST: 'INSUFFICIENT_REST',
  SKILL_MISMATCH: 'SKILL_MISMATCH',
  UNAVAILABLE: 'UNAVAILABLE',
  LOCATION_NOT_ALLOWED: 'LOCATION_NOT_ALLOWED',
  OVERTIME_WARNING: 'OVERTIME_WARNING',
  OVERTIME_BLOCK: 'OVERTIME_BLOCK',
  DAILY_OVERTIME_WARNING: 'DAILY_OVERTIME_WARNING',
  DAILY_OVERTIME_BLOCK: 'DAILY_OVERTIME_BLOCK',
  CONSECUTIVE_DAYS_WARNING: 'CONSECUTIVE_DAYS_WARNING',
  CONSECUTIVE_DAYS_BLOCK: 'CONSECUTIVE_DAYS_BLOCK'
} as const

export const CONSTRAINTS = {
  MIN_REST_HOURS: 10,
  WEEKLY_WARNING_THRESHOLD: 35,
  WEEKLY_MAX: 40,
  DAILY_WARNING: 8,
  DAILY_MAX: 12,
  MAX_CONSECUTIVE_DAYS: 7,
  WARN_CONSECUTIVE_DAYS: 6,
  MAX_PENDING_SWAPS: 3,
  DROP_EXPIRY_HOURS: 24
} as const

export const PREMIUM_SHIFT = {
  DAYS: [5, 6] as const,
  START_HOUR: 17,
  END_HOUR: 23
} as const

export const DEFAULT_CUTOFF_HOURS = 48
